### ISSUE TITLE
TIF image to JPG conversion error

### ISSUE THREAD

**Issue by szekelygobe** [ImageMagick/ImageMagick#1091]
Hi! 

I'm getting this error when I want to convert a TIF file to JPG:
_convert: improper image header `000012331410.TIF' @ error/tiff.c/ReadTIFFImage/1733._

I'm using latest version of imageMagick on Mac / High Sierra
_ImageMagick 7.0.7-28 Q16 x86_64 2018-03-25_

The results of the _identify_  command: 
_000012331410.TIF TIFF 912x628 912x628+0+0 1-bit Bilevel Gray 2440B 0.000u 0:00.000_

Thank you.

**Comment by fmw42** [comment]
Can you provide an example tiff file that fails?  If not, what is the compression type used in the TIFF?What was your exact command line? Note that in IM 7, convert is replaced with magick. Does that help?

Does the following work?

```
magick logo: -threshold 50% -type bilevel logo.tif
magick logo.tif logo.jpg
```

The above commands work fine for me on IM 7.0.7.28 Q16 Mac OSX Sierra with 

    TIFF* TIFF      rw+   Tagged Image File Format (**LIBTIFF, Version 4.0.9**)
      JPG* JPEG      rw-   Joint Photographic Experts Group JFIF format (**90**)

If so, then check your versions of libtif and libjpeg.  Also check the colorspace and compression of your tiff with `magick identify -verbose 000012331410.TIF`

**Comment by fmw42** [comment]
That says that it is either malformed or a format that libtiff cannot read. I tried with IM 6.9.9.40 and 7.0.7.28 and get the same message with LIBTIFF, Version 4.0.9 and JPG (90). However, the file opens with Mac Preview fine. So I suspect it is an issue with libtiff and CCIT Group 4.

**Comment by szekelygobe** [comment]
Can you try pleas with libtiff 4.0.8 ?

**Comment by fmw42** [comment]
I personally cannot easily downgrade my libtiff. Perhaps one of the developers can do that. But perhaps you should first try libtiff 4.0.8 and 4.0.9 stand alone to convert your TIFF. If 4.0.9 fails and 4.0.8 works, then you should report that to the LIBTIFF development team.

**Comment by fmw42** [comment]
Thanks, Dirk.

**Comment by szekelygobe** [comment]
I'm having problems downgrading libtiff. Can you help me with that or point me to some documentaton or tutorials. (I have googled with no luck :( )

**Comment by szekelygobe** [comment]
I have a project that I'm working on, would be nice to know when will IM be coming out.

**Comment by reply2srij** [comment]
> 

Can you please let me know which version this issue was fixed in?

**Comment by dlemstra** [comment]
This was fixed in version `7.0.7-29`.

**Comment by reply2srij** [comment]
> Convert Tiff to PNG error #4671

Thank you for the response! I am still facing a similar issue using 7.0.8 (Ref: Convert Tiff to PNG error #4671)

**Comment by fmw42** [comment]
If it is just missing the photometric interpretation, you can add it using EXIFTOOL. Then ImageMagick may be able to open it and convert it.
