### ISSUE TITLE
-morphology EdgeIn with alpha channel difference between ImageMagick 6 and 7

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1298]
There is a difference between 6.9.10-11 and 7.0.8-11.

```
convert -size 100x100 xc:none -fill none  \
        -stroke brown -strokewidth 10 -draw 'rectangle 20,20 80,80' square.png
convert square.png -channel a -morphology EdgeIn Diamond edgein_square.png
```
The result is:
6.9.10-11
![image](https://user-images.githubusercontent.com/4067843/45208526-11955e00-b28b-11e8-9d06-43f7ad8ad161.png)
7.0.8-11
![image](https://user-images.githubusercontent.com/4067843/45208563-2a057880-b28b-11e8-9ce6-747ac3095430.png)

I think as a consequence,
```
convert shape.gif -channel A -morphology EdgeIn Diamond  shape_edge_pixels.gif
```
as part of usage [example](https://www.imagemagick.org/Usage/canvas/#sparse_fill) does not work for 7.0.8-11 as long as I test correctly.

**Comment by fmw42** [comment]
I can confirm this on the same release as above on Mac OSX Sierra

**Comment by pgajdos** [comment]
To add, this was on linux, x86_64.
Feel free to ask me for help in debugging, right direction is needed, though.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Thank you!

I applied the patch against 7.0.8-12 and the result for `edgein_square.png` and `shape_edge_pixels.gif` are now as expected.

However, note that composite.t is now failing:

Set(size=>"100x80") ...
Composite(, gravity=>'Center', compose=>'Difference') ...
  mean-error=0.224799986543637, maximum-error=1
not ok 10

**Comment by pgajdos** [comment]
(It is filing for 7.0.8-12 plus the patch, so might be I am missing some changes.)

**Comment by urban-warrior** [comment]
Reverted our patch and applied a new patch.  The PerlMagick unit tests should work now.  Thanks.

**Comment by pgajdos** [comment]
Thanks.

Testing with 7.0.8-12+870dd03+e40103d+954ba5c.

Testsuite passes, yes, but unfortunately the situation described in the initial comment of this issue is back, if I tested correctly.

**Comment by urban-warrior** [comment]
We're getting expected results from the ImageMagick master.  You can also download ImageMagick-7.0.8-13.  Let us know if it works for you.

**Comment by pgajdos** [comment]
In retest, I am getting expected results, too. Sorry for the comment I made four days ago, I tested incorrectly. Consider this issue fixed. Thanks a lot!

**Comment by rodlie** [comment]
Fixes added to 7.0.8-13 regarding this issue breaks the following for me:

```
convert -alpha on magick:logo -morphology Edge Diamond:2 output.png
```
If the image has an alpha the result is empty.

Works fine on 6.9.10-52 and 7.0.8-12. Breaks on 7.0.8-13 and beyond (7.0.8-52).

**Comment by fmw42** [comment]
Your syntax is incorrect for IM 7 (using 7.0.8.52). Use magick not convert. Read the input first. Use -alpha activate or -alpha set, not -alpha on. There is no magick:logo. It is logo: 

But I do not understand why you need to turn on alpha when logo has no alpha. A proper command would be:

`magick logo: -morphology Edge Diamond:2 output.png`

or

`magick logo: -alpha set -channel rgb -morphology Edge Diamond:2 output.png`


If I do 

`magick logo: -alpha activate -morphology Edge Diamond:2 output.png`

or

`magick logo: -alpha set -morphology Edge Diamond:2 output.png`

Then I do get your transparent result.

**Comment by rodlie** [comment]
The command was to illustrate the issue, I'm using Magick++. If the input image has alpha (always in my case) then the output is empty.

But applying just to RGB may be a workaround for my issue.

**Comment by fmw42** [comment]
This works for me on IM 7.0.8.52.

```
magick logo: -transparent white logot.png
magick logot.png -alpha activate -morphology Edge Diamond:2 output.png
```

![output](https://user-images.githubusercontent.com/13458218/60751868-1e014a80-9f72-11e9-9fba-1607bb41c191.png)

**Comment by rodlie** [comment]
Source image: https://natron.fxarena.net/misc/image.miff

```
Version: ImageMagick 7.0.8-53 Q32 x86_64 2019-07-06 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.0) 
Delegates (built-in): bzlib fontconfig freetype lcms ltdl lzma png zlib
```
```
magick image.miff -morphology Edge Diamond:2 output.png
```
or
```
image.morphology(Magick::EdgeMorphology,Magick::DiamondKernel,"2");
```
Produces an empty image.

On 6.9.10-52 or 7.0.8-12 I get:
![output](https://user-images.githubusercontent.com/34516798/60752103-7dd31200-9fc1-11e9-9b9f-8d774323257c.jpg)

**Comment by fmw42** [comment]
Your image is not empty. But with IM 7, you should add -channel rgb. IM 7 keeps the alpha channel by default when processing, unlike IM 6, which did not. Your alpha is a constant fully opaque. When processed by the edge detector, it has no edges and so changes to fully 0 alpha, which is transparent.

`magick image.miff -channel rgb -morphology Edge Diamond:2 output.png`

**Comment by rodlie** [comment]
Ok, thanks for the help and information.
