### ISSUE TITLE
magick outputs truncated files when using OpenCL on Intel in some cases

### ISSUE THREAD

**Issue by Myobyte** [ImageMagick/ImageMagick#3473]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-5, others

### Operating system

Windows

### Operating system, version and so on

Windows 10, several recent versions

### Description

In some cases, magick outputs a truncated file. Example command: `magick a.bmp -resize 20%x20% bmp:- > b.bmp`
The issue is related to OpenCL; setting MAGICK_OCL_DEVICE=false fixed the problem everywhere.

The same command worked fine on some machines and failed on others.
All the machines that failed were laptops with an Intel CPU, some with a discrete Nvidia card, some with only Intel HD.
All AMD machines worked fine.

For this command, it only fails when using stdout output. Using `magick a.bmp -resize 20%x20% bmp:b.bmp` instead works fine. This is the case even for some complex commands with only one step accelerated by OpenCL. For example, a complex command that does a resize first failed if the final output was stdout, but worked fine with a file output.

When the problem occurs, the file is always truncated to a multiple of 16KB. Bigger expected outputs give bigger truncated files, as if the output is "rounded down" to a 16KB or bigger boundary. The truncated file is exactly as expected, just that the end is missing (for bmp, padding with black gives the expected image, save the missing part).

### Steps to Reproduce

Use a machine with an Intel HD.
Make sure magick will use OpenCL (built with OpenCL support, MAGICK_OCL_DEVICE set to true).
Create an arbitrary bmp file with a reasonable size (ex: 500x500).
`magick a.bmp -resize 20%x20% bmp:- > b.bmp`

I am convinced that issue #3443 is the same problem, but I felt that I should open another issue given the large difference in details. Feel free to delete or merge if you feel otherwise.
Issue #3470 may be related, but this is only a guess. In my case, complex magick commands with a resize in the chain could "gracefully" fail saying a temp file had insufficient data, or missing rows, depending on the format.

**Comment by dlemstra** [comment]
Resolved in release 7.0.11-6.

**Comment by Myobyte** [comment]
I'd argue that the issue is not fixed. Now that OpenCL is disabled by default it is unlikely to encounter the issue by chance, which is good (thank you for that !). However the underlying OpenCL is still broken in 7.0.11-6 if OpenCL is enabled, which could happen if someone tinkered with MAGICK_OCL_DEVICE before and left it on.

**Comment by dlemstra** [comment]
If you can still reproduce it with OpenCL enabled I will take a look at it.

**Comment by Myobyte** [comment]
I tested with a fresh download, with --version `ImageMagick 7.0.11-6 Q16 x64 2021-04-03`, and the problem is still here. I didn't test as much but I see no differences (except that I now have to set MAGICK_OCL_DEVICE=true explicitly).

**Comment by dlemstra** [comment]
I am unable to reproduce your issue with the latest version of ImageMagick @Myobyte (I temporary logged which device was being used)

```
I:\issues\im7\3473>identify a.bmp
a.bmp BMP 3200x2400 3200x2400+0+0 8-bit sRGB 21.9728MiB 0.547u 0:00.551

I:\issues\im7\3473>magick a.bmp -resize 20%x20% c.bmp
Using OpenCL device: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

I:\issues\im7\3473>type check.bat
@echo off

for /L %%G IN (1,1,100) DO (
  magick a.bmp -resize 20%%x20%% bmp:- > b.bmp
  fc b.bmp c.bmp > NUL
  if errorlevel 1 (
    echo Different output after %%G times
    goto :eof
  )
)

echo No difference found

I:\issues\im7\3473>check.bat
No difference found

```

**Comment by Myobyte** [comment]
I tested again but now trying to see which OpenCL device was used and discovered another unrelated problem:
My PC has two OpenCL devices : `GeForce GTX 1060` and `Intel(R) UHD Graphics 630`. The problem is, `AutoSelectOpenCLDevices()` will choose the NVIDIA device because it has the lowest score, and do so by disabling the others. But just after this there is code to disable NVIDIA devices, which leaves the clEnv with no devices at all. The code falls back on CPU even though the Intel UHD had a much lower score than the CPU. Should I create another issue for this ?

Coming back to the original problem, it seems that because of the above problem, `AccelerateResizeImage` returns NULL and OpenCL is not actually used, but magick _still_ fails. Also, when disabling manually the NVIDIA device (using device manager), it correctly uses OpenCL with device `Intel(R) UHD Graphics 630`, and also fails. In both cases, setting MAGICK_OCL_DEVICE to false resolves the problem.

About your test, the i7-9700K should also have an UHD 630, but in your case it is not used ? I clearly get `device->name` = `Intel(R) UHD Graphics 630`, and not the CPU name. Do you have the Intel HD drivers installed ? Although the problem seems really weird to me, and maybe not entirely because of OpenCL, the main trigger that I see is the presence of Intel HD. We tested 7 different machines, the 4 that failed had an Intel CPU with Intel HD, the 3 that didn't fail had an AMD CPU, so this is very suspicious.

**Comment by dlemstra** [comment]
Thanks for reporting the issue with disabling NVIDIA devices to late, I just pushed a fix for this. But this will only work if the platform of your Intel device is not also NVIDIA. I don't know why the name of my device is different but maybe this is because the AMD OpenCL driver is used? This is the context of my `ImagemagickOpenCLDeviceProfile.xml` file:

```xml
<devices>
  <device name="CPU" score="6.913"/>
  <device platform="AMD Accelerated Parallel Processing" vendor="Advanced Micro Devices, Inc." 
          name="Ellesmere" version="2348.3" maxClockFrequency="1266"
          maxComputeUnits="36" score="0.482" />
  <device platform="AMD Accelerated Parallel Processing" vendor="Advanced Micro Devices, Inc."
          name="Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz" version="2348.3 (sse2,avx)" maxClockFrequency="3600" 
          maxComputeUnits="8" score="1.714" />
</devices>
```

Are you sure you are testing this with the latest release on all those machines? Version `7.0.11-5` was broken and should not be used.

**Comment by Myobyte** [comment]
I did most of the tests with official builds, none of them was 7.0.11-5. I then did a few test with a self built 7.0.11-5 with the null check problem fixed locally.
My xml is as follow:
```
<devices>
  <device name="CPU" score="1.697"/>
  <device platform="NVIDIA CUDA" vendor="NVIDIA Corporation" name="GeForce GTX 1060" version="457.20" maxClockFrequency="1670" maxComputeUnits="10" score="0.3745"/>
  <device platform="Intel(R) OpenCL HD Graphics" vendor="Intel(R) Corporation" name="Intel(R) UHD Graphics 630" version="27.20.100.8681" maxClockFrequency="1000" maxComputeUnits="23" score="0.4221"/>
</devices>
```
My CPU is a laptop i5-8300H.
The two GPU have different platforms. The fact that you don't have the `OpenCL HD Graphics` platform makes me think that you don't have the Intel HD drivers, but I am not sure at all about that.
I didnt use powershell, also the initial problem was encountered with magick invoked directly by another process, with pipes, so no shell was involved.

Other that than, I just found something very interesting. After changing the configurations and test files a bit, I stumbled across a proper crash in Visual Studio, which could very well be the actual cause of this problem.
Magick crashes in `RelinquishMagickCLEnv()`, on `openCL_library->clReleaseContext(clEnv->contexts[i]);`. The `clEnv->contexts` seems to be valid, but the actual content of the contexts (`clEnv->contexts[i]`), is uninitialized (`0xcd` pattern). In a release build, this crash is silent, and the file is partially filled, which make it hard to notice. I did a quick test removing the context release, and the command was successful. Alternatively, adding a `fflush(stdout);` just before the crashing release also solves the problem, so I think what is actually happening is just that the stdout output is cut short by the crash.

**Comment by dlemstra** [comment]
Thanks for all the research @Myobyte. It looks like we were missing a memset in the OpenCL initialization, not sure if that was the root cause though.

**Comment by Myobyte** [comment]
Thanks for the fix. That did fix this particular crash, but unfortunately the truncation problem remains, so there is probably something else. Interestingly, the problem is still fixed when either removing the `clReleaseContext()` or adding `fflush(stdout)` just before, even though the release doesn't crash anymore. I am not sure how to interpret that.

**Comment by dlemstra** [comment]
What happens if you replace `RelinquishMagickCLDevice` with this:

```c
static MagickCLDevice RelinquishMagickCLDevice(MagickCLDevice device)
{
  if (device == (MagickCLDevice) NULL)
    return((MagickCLDevice) NULL);

  device->platform_name=RelinquishMagickMemory(device->platform_name);
  device->vendor_name=RelinquishMagickMemory(device->vendor_name);
  device->name=RelinquishMagickMemory(device->name);
  device->version=RelinquishMagickMemory(device->version);
  if (device->program != (cl_program) NULL)
    (void) openCL_library->clReleaseProgram(device->program);
  while (device->command_queues_index >= 0)
    ReleaseOpenCLCommandQueue(device,device->command_queues[
      device->command_queues_index--]);
  RelinquishSemaphoreInfo(&device->lock);
  return((MagickCLDevice) RelinquishMagickMemory(device));
}
```

**Comment by dlemstra** [comment]
Yeah I missed that. Wanted to test if we needed the flush. Does this fix the issue:

```c
  while (device->command_queues_index >= 0)
    {
      (void) openCL_library->clFlush(
        device->command_queues[device->command_queues_index]);
      (void) openCL_library->clReleaseCommandQueue(
        device->command_queues[device->command_queues_index--]);
    }
```

**Comment by Myobyte** [comment]
Both `clFinish` and `clFlush` fail to fix the issue. It does work if I remove the `clReleaseCommandQueue` just after.

**Comment by dlemstra** [comment]
It looks like something inside OpenCL is in an incorrect state. I cannot reproduce the issue so I am hoping that you can find where we break it.

**Comment by Myobyte** [comment]
I'll try to find something, but that may take some time since I'm not familiar with magick or OpenCL.
