### ISSUE TITLE
7.0.4-6 Failed test on 32bits build

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick#363]
```
Line: 63 Color("green") is #000080800000 rather than #000080800000
1 failures
not ok
FAIL: Magick++/tests/tests.tap 6
```

**Comment by mikayla-grace** [comment]
We corrected this finite precision problem in the 16th decimal place so you can safely ignore this unit test failure.

**Comment by remicollet** [comment]
Still failing the same way with the patch applied (which is only in the ImageMagick6 branch)

**Comment by remicollet** [comment]
FYI 6.9.7-6 test suite is ok, without this patch (but HDRI is off by default in 6, while on in 7)

**Comment by urban-warrior** [comment]
The  https://github.com/ImageMagick/ImageMagick/commit/9024139f4bf2f029a05ffaeaaf2158afef342785 commit fixed the problem for us.  We're running ImageMagick 7.0.4-7 Q32 x86_64 and the color unit tests complete without complaint.  Without the patch we got the same exception you posted.

**Comment by remicollet** [comment]
@urban-warrior this report is not about x86_64 but i386

**Comment by dlemstra** [comment]
I cannot reproduce your issue one Windows with the latest development build @remicollet. I tested this with an Q16-HDRI x86 build. What kind of platform are you running this on, and what type of build do you have? We could remove the green option from the list if this is causing you problems.

**Comment by remicollet** [comment]
> What kind of platform are you running this on

Linux.
Tried and reproduced on Fedora 22 to 25, RHEL 5 and 6

**Comment by mikayla-grace** [comment]
Let's not remove a unit test, instead we'll fix it.  @remicollet confirm the problem is with Q16 HDRI?  @dlemstra its likely a finite precision problem when using HDRI floating point.  The Magick++ ColorRGB equal (=) operator likely needs to compare the results against MagickEpsilon.  Best practices for floating point equality is to compare against MagickEpsilon.  For example: ```if (fabs(red-Red) < MagickEpsilon) then // equal```
