### ISSUE TITLE
SVG Incorrect render using inkscape (OK through inkscape GUI)

### ISSUE THREAD

**Issue by ramubhai** [ImageMagick/ImageMagick#3773]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-14

### Operating system

Windows

### Operating system, version and so on

10 latest updated

### Description

I have a svg file showing 12 numbers in a circle. When I open it in Inkscape, numbers are in perfect circle. However when I convert from svg to png using command line, the generated image is distorted. Using the -verbose flag, I can confirm that Inkscape is indeed being used to render the image, but the output is not correct. Ataching both input and output file. Check the input in Inkscape. SVG is OK.

Content of SVG file is as following.
Since SVG file upload is not being allowed by GitHub.

<svg height="1080" width="1920"
    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <defs>
        <g id="0">
            <rect width="100%" height="100%" fill="#7f8c8d" /> 
        </g>

        <g id="1">
            <circle cx="960" cy="540" r="500" stroke="black" stroke-width="3" fill="#ecf0f1" />

            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(30,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(60,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(90,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(120,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(150,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(180,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(210,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(240,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(270,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(300,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(330,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(360,960,540)"/>
            
            <text  text-anchor="middle" x="1180" y="233" font-size="8em" fill="#7f8c8d">1</text>
            <text  text-anchor="middle" x="1341" y="380" font-size="8em"  fill="#7f8c8d">2</text>
            <text  text-anchor="middle" x="1400" y="580" font-size="8em"  fill="#7f8c8d">3</text>
            <text  text-anchor="middle" x="1341" y="780" font-size="8em"  fill="#7f8c8d">4</text>
            <text  text-anchor="middle" x="1180" y="926" font-size="8em"  fill="#7f8c8d">5</text>
            <text  text-anchor="middle" x="960" y="980" font-size="8em"  fill="#7f8c8d">6</text>
            <text  text-anchor="middle" x="740" y="926" font-size="8em"  fill="#7f8c8d">7</text>
            <text  text-anchor="middle" x="578" y="780" font-size="8em"  fill="#7f8c8d">8</text>
            <text  text-anchor="middle" x="540" y="580" font-size="8em"  fill="#7f8c8d">9</text>
            <text  text-anchor="middle" x="578" y="380" font-size="8em"  fill="#7f8c8d">10</text>
            <text  text-anchor="middle" x="740" y="233" font-size="8em"  fill="#7f8c8d">11</text>
            <text  text-anchor="middle" x="960" y="180" font-size="8em"  fill="#7f8c8d">12</text>
            
        </g>

    </defs>

    <use xlink:href="#0"/>
    <use xlink:href="#1"/>
    
</svg>

### Steps to Reproduce

>magick convert dial.svg dial.png

Than check the generated png. It is different from what is being shown in SVG. Output of above command is reproduced below. Actual image is being attached with bug report.

>magick convert -verbose dial.svg dial.png
"inkscape" "C:/Users/xxxxxxxxxx/AppData/Local/Temp/magick-yP4mnRRuIimgEQOF5-__5ynZrQZC9bWv" --export-eps="C:/Users/xxxxxxxxxx/AppData/Local/Temp/magick-4ct0nluDG7g36SRGmwFTPJOot73GulYB.png" --export-dpi="96" --export-background="rgb(100%,100%,100%)" --export-background-opacity="0.99999999999900002212" > "C:/Users/xxxxxxxxxx/AppData/Local/Temp/magick-rDfFBz7NXG__6gkt4CIFk9Ut_EuJK-XG" 2>&1
dial.svg SVG 1920x1080 1920x1080+0+0 16-bit sRGB 3402B 0.141u 0:00.835
dial.svg=>dial.png SVG 1920x1080 1920x1080+0+0 16-bit sRGB 3402B 0.719u 0:00.385

### Images

![dial](https://user-images.githubusercontent.com/182385/120390481-5fabf300-c34b-11eb-9700-f43547f6a738.png)

**Comment by ramubhai** [comment]
Apparently SVG headers are being trimmed out from Description. Adding Header here again without parenthesis.

svg height="1080" width="1920"
    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"

defs
        <g id="0">
            <rect width="100%" height="100%" fill="#7f8c8d" /> 
        </g>

        <g id="1">
            <circle cx="960" cy="540" r="500" stroke="black" stroke-width="3" fill="#ecf0f1" />

            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(30,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(60,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(90,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(120,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(150,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(180,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(210,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(240,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(270,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(300,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(330,960,540)"/>
            <circle cx="960" cy="50" r="5" stroke-width="0" fill="#e67e22" transform="rotate(360,960,540)"/>
            
            <text  text-anchor="middle" x="1180" y="233" font-size="8em" fill="#7f8c8d">1</text>
            <text  text-anchor="middle" x="1341" y="380" font-size="8em"  fill="#7f8c8d">2</text>
            <text  text-anchor="middle" x="1400" y="580" font-size="8em"  fill="#7f8c8d">3</text>
            <text  text-anchor="middle" x="1341" y="780" font-size="8em"  fill="#7f8c8d">4</text>
            <text  text-anchor="middle" x="1180" y="926" font-size="8em"  fill="#7f8c8d">5</text>
            <text  text-anchor="middle" x="960" y="980" font-size="8em"  fill="#7f8c8d">6</text>
            <text  text-anchor="middle" x="740" y="926" font-size="8em"  fill="#7f8c8d">7</text>
            <text  text-anchor="middle" x="578" y="780" font-size="8em"  fill="#7f8c8d">8</text>
            <text  text-anchor="middle" x="540" y="580" font-size="8em"  fill="#7f8c8d">9</text>
            <text  text-anchor="middle" x="578" y="380" font-size="8em"  fill="#7f8c8d">10</text>
            <text  text-anchor="middle" x="740" y="233" font-size="8em"  fill="#7f8c8d">11</text>
            <text  text-anchor="middle" x="960" y="180" font-size="8em"  fill="#7f8c8d">12</text>
            
        </g>

    </defs>

    <use xlink:href="#0"/>
    <use xlink:href="#1"/>
    
/svg

**Comment by urban-warrior** [comment]
@dlemstra, can you check the `inkscape` delegate command-line.  It differs from the Linux version where we get expected results.  Inkscape is version 1.1 and we have ` --export-filename` whereas the Windows delegate uses `--export-eps` which involves Ghostscript to render the EPS results-- perhaps the source of the flaw.

**Comment by dlemstra** [comment]
I just pushed a patch for fix this for Windows. Can you change `--export-eps` to `--export-filename` inside `delegates.xml` and test this again @ramubhai?

**Comment by ramubhai** [comment]
> I just pushed a patch for fix this for Windows. Can you change `--export-eps` to `--export-filename` inside `delegates.xml` and test this again @ramubhai?

It doesn't seem to fix it. I am still getting same wrong output.

Microsoft Windows [Version 10.0.19043.985]
(c) Microsoft Corporation. All rights reserved.
C:\Users\xxxxxxxxxx\Desktop>magick convert -verbose dial.svg dial.png
"inkscape" "C:/Users/xxxxxxxxxx/AppData/Local/Temp/magick-R8t1zKq3qxmdAqVSnaOdeVwR3lDFdi5Z" --export-filename="C:/Users/xxxxxxxxxx/AppData/Local/Temp/magick-f8rmT6HBVjVsuQeyN1huAgrEbo3haPd4.png" --export-dpi="96" --export-background="rgb(100%,100%,100%)" --export-background-opacity="0.99999999999900002212" > "C:/Users/xxxxxxxxxx/AppData/Local/Temp/magick-VRwHq-DC1mpgqH53qYj_9mGLHiSRX_56" 2>&1
dial.svg SVG 1920x1080 1920x1080+0+0 16-bit sRGB 3015B 0.109u 0:05.934
dial.svg=>dial.png SVG 1920x1080 1920x1080+0+0 16-bit sRGB 3015B 0.797u 0:00.350
C:\Users\xxxxxxxxxx\Desktop>


I am pasting the modified line in delegates.xml also for Reference.
<delegate decode="svg:decode" stealth="True" command="&quot;inkscape&quot; &quot;%s&quot; --export-filename=&quot;%s&quot; --export-dpi=&quot;%s&quot; --export-background=&quot;%s&quot; --export-background-opacity=&quot;%s&quot; &gt; &quot;%s&quot; 2&gt;&amp;1"/>
  

One quick observation looking at the inkscape output. Why it is creating a 16bit sRGB instead of 8 bit? There is nothing in SVG indicating it to be 16 bit / color channel.  Following simple command gives correct PNG output.

C:\Users\xxxxxxxxxx\Desktop>inkscape --export-type="png" dial.svg
Background RRGGBBAA: ffffff00
Area 0:0:1920:1080 exported to 1920 x 1080 pixels (96 dpi)
C:\Users\xxxxxxxxxx\Desktop>

Perhaps it is a bug in inkscape 16bit rendering path?
