### ISSUE TITLE
compare reports large differences between equivalent ISO/IEC 15444-4 reference images

### ISSUE THREAD

**Issue by benjamingeer** [ImageMagick/ImageMagick#409]
The [ISO/IEC 15444-4:2004](https://www.iso.org/standard/39079.html) standard includes a set of 9 pairs of reference images in JPEG2000 and TIFF formats, to be used for testing JPEG2000 software. For each JPEG2000 image, there is an equivalent TIFF image. However, the `compare` program reports that some of these image pairs are very different.

Operating system: macOS 10.12.3.

ImageMagick version:

```bash
$ compare -version
Version: ImageMagick 7.0.5-3 Q16 x86_64 2017-03-24 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib freetype jng jp2 jpeg lcms ltdl lzma png tiff xml zlib
```

To reproduce:

1. Download the files in the directories `reference_jp2` and ` testfiles_jp2` at http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_IEC_15444-4_2004_Conformance_Testing/ and save them in directories with the same names.

2. Open a Bash shell in the parent directory, and copy and paste this into the shell:

```bash
for i in 1 2 3 4 5 6 7 8 9; do echo -n "Image $i: "; echo $(compare -metric PAE reference_jp2/jp2_$i.tif testfiles_jp2/file$i.jp2 null:); done
```

Expected results:

```
Image 1: 0 (0)
Image 2: 0 (0)
Image 3: 0 (0)
Image 4: 0 (0)
Image 5: 0 (0)
Image 6: 0 (0)
Image 7: 0 (0)
Image 8: 0 (0)
Image 9: 0 (0)
```

Actual results:

```
Image 1: 0 (0)
Image 2: 50629 (0.772549)
Image 3: 53970 (0.823529)
Image 4: 0 (0)
Image 5: 32382 (0.494118)
Image 6: 240.055 (0.003663)
Image 7: 24626 (0.375769)
Image 8: 4883 (0.0745098)
Image 9: 0 (0)
```

**Comment by mikayla-grace** [comment]
We are not detecting the colorspace properly.  Some of the images are in the Rec601YCbCr colorspace.  If we force that colorspace we get expected results:

```
convert file2.jp2 -set colorspace Rec601YCbCr -colorspace sRGB file2-sRGB.jp2
compare -metric rmse jp2_2.tif file2-sRGB.jp2 null:
```

We still get a small distortion (0.0078) due to the colorspace conversion from Rec601YCbCr  to sRGB to match the requirements of the TIFF image.

We will apply a patch soon to properly detect the colorspace in JP2 images.

**Comment by benjamingeer** [comment]
That's great, thanks! Looking forward to the patch.

**Comment by benjamingeer** [comment]
Could we have an update on the status of this issue?

**Comment by dlemstra** [comment]
The patch has been applied on the 25th of March and we publish a new release 14 days ago. Your issue should be resolved in the current version of ImageMagick.

**Comment by mikayla-grace** [comment]
Here's an example with the latest ImageMagick release:

```
-> convert file2.jp2 -colorspace sRGB file2-sRGB.jp2
-> compare -metric rmse jp2_2.tif file2-sRGB.jp2 null:
193.04 (0.0029456)        
```

**Comment by benjamingeer** [comment]
With the latest release compiled from source, I still get the same results that I originally reported:

```
$ /opt/bin/convert --version
Version: ImageMagick 7.0.5-5 Q16 x86_64 2017-05-09 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib fontconfig freetype gvc jng jp2 jpeg lcms lzma png tiff webp x xml zlib
$ for i in 1 2 3 4 5 6 7 8 9; do echo -n "Image $i: "; echo $(/opt/bin/compare -metric PAE reference_jp2/jp2_$i.tif testfiles_jp2/file$i.jp2 null:); done
Image 1: 0 (0)
Image 2: 50629 (0.772549)
Image 3: 53970 (0.823529)
Image 4: 0 (0)
Image 5: 32382 (0.494118)
Image 6: 240.055 (0.003663)
Image 7: 24626 (0.375769)
Image 8: 4883 (0.0745098)
Image 9: 0 (0)
```

Am I doing something wrong?

**Comment by mikayla-grace** [comment]
Some of the JP2 reference images are in the YUV colorspace, whereas the TIFF images are sRGB.  As a result, a high distortion is returned.  You must explicitly convert to sRGB before the compare with the `-colorspace SRGB` option.

**Comment by benjamingeer** [comment]
OK, but `compare` still reports a lot of distortion with images 5 and 7:

```
$ convert testfiles_jp2/file5.jp2 -colorspace sRGB file5-sRGB.jp2
$ compare -metric rmse reference_jp2/jp2_5.tif file5-sRGB.jp2 null:
8933.67 (0.136319)
$ compare -metric PAE reference_jp2/jp2_5.tif file5-sRGB.jp2 null:
32382 (0.494118)
$ convert testfiles_jp2/file7.jp2 -colorspace sRGB file7-sRGB.jp2
$ compare -metric rmse reference_jp2/jp2_7.tif file7-sRGB.jp2 null:
12268.4 (0.187204)
$ compare -metric PAE reference_jp2/jp2_7.tif file7-sRGB.jp2 null:
24626 (0.375769)
```

Also, why does `identify -verbose` report different colorspaces from `identify` without `-verbose`? Without `-verbose`, it says that all the images are sRGB.

```
$ identify -verbose testfiles_jp2/file3.jp2 | grep Colorspace
  Colorspace: Rec601YCbCr
$ identify testfiles_jp2/file3.jp2
testfiles_jp2/file3.jp2 JP2 480x640 480x640+0+0 8-bit sRGB 242213B 0.000u 0:00.000
$ identify -verbose testfiles_jp2/file4.jp2 | grep Colorspace
  Colorspace: Gray
$ identify testfiles_jp2/file4.jp2
testfiles_jp2/file4.jp2 JP2 768x512 768x512+0+0 8-bit sRGB 220443B 0.000u 0:00.000
```

**Comment by benjamingeer** [comment]
Also, `identify -verbose` says that JP2 images 5 and 7 are already sRGB, so there should be no need to convert to sRGB before comparing:

```
$ identify -verbose testfiles_jp2/file5.jp2 | grep Colorspace
  Colorspace: sRGB
$ identify -verbose testfiles_jp2/file7.jp2 | grep Colorspace
  Colorspace: sRGB
```

**Comment by dlemstra** [comment]
@benjamingeer Do we still need to investigate this issue?
