### ISSUE TITLE
detect memmory leak in ImageMagick while reading exr file

### ISSUE THREAD

**Issue by huanggh666** [ImageMagick/ImageMagick#4535]
### ImageMagick version

7.1.0-17 Q16-HDRI x86_64 2021-11-21

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04 bionic

### Description

I identity a memory leak issue in ImageMagick while fuzzing. I  guess it is the issue in OpenEXR library at fisrt and I submmit an [issue in OpenEXR](https://github.com/AcademySoftwareFoundation/openexr/issues/1210). But it does not report memory leak in OpenEXR. It may be an issue in ImageMagick. I pull the latest code of ImageMgick in github and rebuild it. The report is a little different than before.

### Steps to Reproduce

Compile and install the programs using AFL++ with ASAN. I install OpenEXR-3.1 libary which would be built in ImageMagick.
```
export AFL_USE_ASAN=1
CC=afl-cc CXX=afl-c++ ./configure
make && make install
./magick poc_openexr /dev/null
```
Here is the ASAN's log
```
magick: width or height exceeds limit `openexr/exr_eco_bk/crashes/id:000000,sig:06,src:001834,op:havoc,rep:16' @ error/cache.c/OpenPixelCache/3688.

=================================================================
==75628==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x4db510 in __interceptor_malloc (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4db510)
    #1 0x7f27c16fa297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x4db510 in __interceptor_malloc (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4db510)
    #1 0x7f27c934a469 in AcquireMagickMemory /home/hgh/programs/ImageMagick_pure/MagickCore/memory.c:558:10
    #2 0x7f27c934a469 in AcquireCriticalMemory /home/hgh/programs/ImageMagick_pure/MagickCore/memory.c:634

Indirect leak of 286823458 byte(s) in 63 object(s) allocated from:
    #0 0x4db510 in __interceptor_malloc (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4db510)
    #1 0x7f27c16fa297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)

Indirect leak of 142607232 byte(s) in 1 object(s) allocated from:
    #0 0x4dc148 in __interceptor_posix_memalign (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4dc148)
    #1 0x7f27c5778037 in Imf_3_1::ScanLineInputFile::initialize(Imf_3_1::Header const&) (/usr/local/lib/libOpenEXR-3_1.so.29+0xde037)

Indirect leak of 592 byte(s) in 2 object(s) allocated from:
    #0 0x4db510 in __interceptor_malloc (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4db510)
    #1 0x7f27c16fa297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)
    #2 0x43de79b4c7a646ff  (<unknown module>)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4dc148 in __interceptor_posix_memalign (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4dc148)
    #1 0x7f27c95dd21f in AcquireSemaphoreMemory /home/hgh/programs/ImageMagick_pure/MagickCore/semaphore.c:154:7
    #2 0x7f27c95dd21f in AcquireSemaphoreInfo /home/hgh/programs/ImageMagick_pure/MagickCore/semaphore.c:200
    #3 0x7f27c931d27d in NewLinkedList /home/hgh/programs/ImageMagick_pure/MagickCore/linked-list.c:725:24

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4dc148 in __interceptor_posix_memalign (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4dc148)
    #1 0x7f27c95dd21f in AcquireSemaphoreMemory /home/hgh/programs/ImageMagick_pure/MagickCore/semaphore.c:154:7
    #2 0x7f27c95dd21f in AcquireSemaphoreInfo /home/hgh/programs/ImageMagick_pure/MagickCore/semaphore.c:200
    #3 0x7f27c926db75 in InitializeExceptionInfo /home/hgh/programs/ImageMagick_pure/MagickCore/exception.c:741:24
    #4 0x7f27c926db75 in AcquireExceptionInfo /home/hgh/programs/ImageMagick_pure/MagickCore/exception.c:121

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x4db510 in __interceptor_malloc (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4db510)
    #1 0x7f27c934a469 in AcquireMagickMemory /home/hgh/programs/ImageMagick_pure/MagickCore/memory.c:558:10
    #2 0x7f27c934a469 in AcquireCriticalMemory /home/hgh/programs/ImageMagick_pure/MagickCore/memory.c:634

Indirect leak of 32 byte(s) in 2 object(s) allocated from:
    #0 0x4db510 in __interceptor_malloc (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4db510)
    #1 0x7f27c16fa297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)
    #2 0x3f7fffff  (<unknown module>)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4db510 in __interceptor_malloc (/home/hgh/programs/ImageMagick_pure/build/bin/magick+0x4db510)
    #1 0x7f27c16fa297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)
    #2 0x6e6f68  (<unknown module>)

SUMMARY: AddressSanitizer: 429431626 byte(s) leaked in 74 allocation(s).
```
ImageMagick Version
```
Version: ImageMagick 7.1.0-17 Q16-HDRI x86_64 2021-11-21 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(3.1)
Delegates (built-in): bzlib djvu fontconfig freetype heic jbig jng jp2 jpeg lcms lqr lzma openexr pangocairo png tiff webp x xml zlib
Compiler: gcc (4.2)
```
Seculity Policy
```
Path: /home/hgh/programs/ImageMagick_pure/build/etc/ImageMagick-7/policy.xml
  Policy: Cache
    name: memory-map
    value: anonymous
  Policy: Cache
    name: synchronize
    value: True
  Policy: Resource
    name: list-length
    value: 128
  Policy: Resource
    name: time
    value: 3600
  Policy: Resource
    name: throttle
    value: 0
  Policy: Resource
    name: thread
    value: 4
  Policy: Resource
    name: file
    value: 768
  Policy: Resource
    name: disk
    value: 16EiB
  Policy: Resource
    name: map
    value: 4GiB
  Policy: Resource
    name: memory
    value: 2GiB
  Policy: Resource
    name: area
    value: 100MP
  Policy: Resource
    name: height
    value: 10KP
  Policy: Resource
    name: width
    value: 10KP
  Policy: System
    name: max-memory-request
    value: 256MiB
  Policy: Resource
    name: temporary-path
    value: /tmp
  Policy: Coder
    rights: None
    pattern: MVG
  Policy: Module
    rights: None
    pattern: {PS,PDF,XPS}
  Policy: Delegate
    rights: None
    pattern: HTTPS
  Policy: Path
    rights: None
    pattern: @*
  Policy: System
    name: shred
    value: 2
  Policy: System
    name: precision
    value: 6
  Policy: System
    name: font
    value: /path/to/unicode-font.ttf

Path: [built-in]
  Policy: Undefined
    rights: None
magick: delegate library support not built-in '' (policy requires anonymous memory mapping) @ error/cache.c/OpenPixelCache/3674.
```

### Images

[poc_openexr.zip](https://github.com/ImageMagick/ImageMagick/files/7639790/poc_openexr.zip)

**Comment by dlemstra** [comment]
Thanks for reporting this. Your report fixed an memory leak before we published a release with that bug. Can you give it another try with the latest commit?

**Comment by huanggh666** [comment]
Yes, I have tried. But it seems that the issue still exists. I clone this repo with cmd:
`git clone --depth=1 https://github.com/ImageMagick/ImageMagick.git`,
and rebuild it as the reproduce steps. The ASAN's log is:
```
magick: width or height exceeds limit `poc_openexr' @ error/cache.c/OpenPixelCache/3688.

=================================================================
==37926==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x4db2d0 in __interceptor_malloc (/home/hgh/programs/ImageMagick_run/build/bin/magick+0x4db2d0)
    #1 0x7ff3599d0297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)

Indirect leak of 286823387 byte(s) in 62 object(s) allocated from:
    #0 0x4db2d0 in __interceptor_malloc (/home/hgh/programs/ImageMagick_run/build/bin/magick+0x4db2d0)
    #1 0x7ff3599d0297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)

Indirect leak of 142607232 byte(s) in 1 object(s) allocated from:
    #0 0x4dbf08 in __interceptor_posix_memalign (/home/hgh/programs/ImageMagick_run/build/bin/magick+0x4dbf08)
    #1 0x7ff35c06c037 in Imf_3_1::ScanLineInputFile::initialize(Imf_3_1::Header const&) (/usr/local/lib/libOpenEXR-3_1.so.29+0xde037)

Indirect leak of 592 byte(s) in 2 object(s) allocated from:
    #0 0x4db2d0 in __interceptor_malloc (/home/hgh/programs/ImageMagick_run/build/bin/magick+0x4db2d0)
    #1 0x7ff3599d0297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)
    #2 0xe23616af61ccbfff  (<unknown module>)

Indirect leak of 32 byte(s) in 2 object(s) allocated from:
    #0 0x4db2d0 in __interceptor_malloc (/home/hgh/programs/ImageMagick_run/build/bin/magick+0x4db2d0)
    #1 0x7ff3599d0297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)
    #2 0x3f7fffff  (<unknown module>)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4db2d0 in __interceptor_malloc (/home/hgh/programs/ImageMagick_run/build/bin/magick+0x4db2d0)
    #1 0x7ff3599d0297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)
    #2 0x6e6f68  (<unknown module>)

SUMMARY: AddressSanitizer: 429431315 byte(s) leaked in 69 allocation(s).
```

**Comment by urban-warrior** [comment]
Those leaks come from the EXR library.  We will check to ensure we are shutting down the OpenEXR library properly but at first glance we cannot find a C API call that frees all OpenEXR memory.
