### ISSUE TITLE
Converting to WEBP via delegates results in silent loss of quality

### ISSUE THREAD

**Issue by pravorskyi** [ImageMagick/ImageMagick#5010]
### ImageMagick version

7.1.0-13

### Operating system

Linux

### Operating system, version and so on

Gentoo/Linux amd64

### Description

If ImageMagick is compiled without `webp` support (accidentally or the maintainer of one of the repositories does it for some reason), then converting the image to WEBP produces a silent quality loss without any warning.

Additional options like "lossless=true" are silently ignored as well.

Do I understand correctly that this is due to delegates.xml? I found this line:
`<delegate decode="png" encode="webp" command="&quot;cwebp&quot; -quiet %Q &quot;%i&quot; -o &quot;%o&quot;"/>`

I see two ways to solve this issue:

- Print a warning to stderr about additional parameters that are ignored.

or

- Make the default conversion lossless. This can potentially lead to slower conversions and larger output files for those who convert to WEBP via delegates. On the other hand, the quality is not lost quietly.

### Steps to Reproduce

* Compile ImageMagick without `webp` support.
* Run `magick input.tiff -define webp:lossless=true output.webp`

Result: The image will be converted to WEBP with a significant loss in quality. Additional options "-define webp:lossless=true" **are ignored without warning**.

**Comment by urban-warrior** [comment]
We fixed the missing `-q` in front of the image compression quality.  With the patch, `magick input.tiff -quality 100 output.webp` produces near lossless compression quality.  If you want lossless, use the Webp delegate library.  To determine if ImageMagick is built with the `libwebp` delegate library, use this command: `magick -list format`.  ImageMagick only defaults to the `cwebp` command-line utility if the delegate library is not included @ build time.

**Comment by pravorskyi** [comment]
Thank you for bringing the problem to your attention.

I still have a question about silently ignored parameters. Is it possible to improve ImageMagick to print a warning about unused/ignored options when it uses `cwebp`?

**Comment by urban-warrior** [comment]
Sure, we'll add it to the list of things to do which numbers in the hundreds.  As ImageMagick is open-source, alternatively, you or another member can contribute a patch and post it as a pull request.
