### ISSUE TITLE
Resized animated WebP has artifacts

### ISSUE THREAD

**Issue by y-guyon** [ImageMagick/ImageMagick#5542]
### ImageMagick version

7.1.0-48 beta

### Operating system

Linux

### Operating system, version and so on

Debian GNU/Linux 12 rodete

### Description

`-resize` an animated WebP with frame windows (only sub-regions are updated) garbles the output.

`-coalesce -resize` an animated WebP with a translucent area (shadow) seems to progressively opacify that area (the shadow grows). This option was suggested in https://github.com/ImageMagick/ImageMagick/issues/4246.

Is there another flag that I missed to obtain the same image between input and output?

I tried ImageMagick at head (https://github.com/ImageMagick/ImageMagick/commit/8ba9e67d34fb860fc4e02d752885bbe8a8e17070 + `./configure` + `make`). I have the same issue with the installed ImageMagick version 6.9.11-60.

### Steps to Reproduce

1. Download [animated_webp_images.zip](https://github.com/ImageMagick/ImageMagick/files/9534112/animated_webp_images.zip) and extract `original.webp`
2. See how the output of `magick original.webp -resize 80x80 resize.webp` is garbled
3. See how the output of `magick original.webp -coalesce -resize 80x80 resize.webp` has a shadow that strengthens over time

### Images

[animated_webp_images.zip](https://github.com/ImageMagick/ImageMagick/files/9534112/animated_webp_images.zip)

**Comment by snibgo** [comment]
"info:" tells us that frames have different sizes with offsets ...
```
f:\web\im>%IMG7%magick original.webp info:
original.webp[0] WEBP 80x80 80x80+0+0 8-bit sRGB 30170B 0.000u 0:00.001
original.webp[1] WEBP 32x36 80x80+6+16 8-bit sRGB 0.000u 0:00.021
original.webp[2] WEBP 47x52 80x80+6+16 8-bit sRGB 0.000u 0:00.036
original.webp[3] WEBP 64x50 80x80+6+20 8-bit sRGB 0.000u 0:00.050
original.webp[4] WEBP 68x64 80x80+6+6 8-bit sRGB 0.000u 0:00.069
original.webp[5] WEBP 70x66 80x80+4+4 8-bit sRGB 0.000u 0:00.083
original.webp[6] WEBP 74x70 80x80+0+0 8-bit sRGB 0.000u 0:00.097
original.webp[7] WEBP 74x66 80x80+0+4 8-bit sRGB 0.000u 0:00.110
original.webp[8] WEBP 70x66 80x80+4+4 8-bit sRGB 0.000u 0:00.123
original.webp[9] WEBP 15x15 80x80+8+6 8-bit sRGB 0.000u 0:00.136
```
... so we need "-layers coalesce", or just "-coalesce".

The input is 80x80 pixels, so resizing to 80x80 doesn't do much, but the output seems fine. We can resize to something else:
```
f:\web\im>%IMG7%magick original.webp -layers coalesce -resize 300x300 x.webp
```
Again, the output seems fine.

Tested with IM v7.1.0-42 on Windows 8.1.

**Comment by y-guyon** [comment]
> ... so we need "-layers coalesce", or just "-coalesce".
> 
> The input is 80x80 pixels, so resizing to 80x80 doesn't do much, but the output seems fine.

As you can see in my original description, the output is not fine with `-coalesce`. The camera's shadow is not constant between frames, it "pulses". Compare `original.webp` and `resize_coalesce.webp` from `animated_webp_images.zip`. Do you obtain a different output with IM v7.1.0-42 on Windows 8.1?

**Comment by dlemstra** [comment]
The problem here is that the `webp` encoder does a call to `-coalesce` and when this is done twice the output is incorrect. We have removed the call to `-coalesce` and this issue should be resolved in the next release.

**Comment by y-guyon** [comment]
@dlemstra
Hi, the problem seems to still exist: https://bugs.chromium.org/p/webp/issues/detail?id=628

**Comment by dlemstra** [comment]
You will need to add `-coalesce` as mentioned here and in that bug report.

**Comment by dlemstra** [comment]
You will need to add that in the most recent releases. We had to change that because of another bug that would happen if we would always perform a `-coalesce` ourselves.

**Comment by y-guyon** [comment]
> I haven't had/made time to investigate this.

That is fine. Could we reopen this issue in the meantime, to signal there is some unexpected behavior? Or is there another tracked issue already?

**Comment by dlemstra** [comment]
No? This is the current behavior. We might make changes in the future but we are not sure if that is even possible or will ever happen. Users will need to add `-coalesce`. This is now the expected behavior so I don't see a reason to reopen this issue.

**Comment by y-guyon** [comment]
> This is now the expected behavior so I don't see a reason to reopen this issue.

Understood.

> Users will need to add `-coalesce`.

How can they find that out?  
Maybe a note in https://imagemagick.org/script/command-line-options.php#resize could help?
