### ISSUE TITLE
ImageMagick is incorrectly reading a tiff image as black and white when it should be gray scale, photoshop, and ImageJ as well as Mac Preview show image fine

### ISSUE THREAD

**Issue by jmilbrandt2** [ImageMagick/ImageMagick#5597]
### ImageMagick version

newest version

### Operating system

Windows

### Operating system, version and so onx

Windows 10 

### Description

I have a 16 bit tif, the values are very low for the dynamic range and so they are being dumped in with black

### Steps to Reproduce

     byte[] data1 = File.ReadAllBytes(fileToDisplay1);
      MemoryStream stream = new MemoryStream(data1);
      MagickImage image = new MagickImage(stream, MagickFormat.Tif);
      
      

### Images

https://drive.google.com/file/d/16Xotc-2CJ6HkEJDysfKBkjClkU1OGiyQ/view?usp=sharing

[mystery.zip](https://github.com/ImageMagick/ImageMagick/files/9657638/mystery.zip)

(https://stackoverflow.com/questions/73860945/image-not-viewable-using-c-sharp-libraries-viewable-in-imagej-or-imagej-online-h/73861281#73861281)

The image is on stack overflow, basically ImageMagick is treating a grayscale image as black and white

**Comment by fmw42** [comment]
Imagemagick sees the data as binary whereas it is grayscale with very low values. 

```
Image:
  Filename: mystery.tif
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 2040x2040+0+0
  Units: PixelsPerInch
  Colorspace: Gray
  Type: Bilevel
  Base type: Grayscale
  Endianness: LSB
  Depth: 16/1-bit
  Channel depth:
    gray: 1-bit
  Channel statistics:
    Pixels: 4161600
    Gray:
      min: 0  (0)
      max: 0 (0)
      mean: 0 (0)
      standard deviation: 0 (0)
      kurtosis: -3
      skewness: 0
      entropy: 0
  Colors: 1
  Histogram:
       4161600: (0,0,0) #000000000000 gray(0)
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: gray(255)
  Border color: gray(223)
  Matte color: gray(189)
  Transparent color: gray(0)
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 2040x2040+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: LZW
  Orientation: TopLeft
  Properties:
    date:create: 2022-09-27T00:43:06+00:00
    date:modify: 2022-09-27T00:42:39+00:00
    date:timestamp: 2022-09-27T00:43:25+00:00
    signature: 28f00fa3c1987b7b8f92961ef3a2d442cca23dbbb7c568b8908cc2fa2271de60
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:photometric: min-is-black
  Artifacts:
    filename: mystery.tif
    verbose: true
  Tainted: False
  Filesize: 48240B
  Number pixels: 4161600
  Pixels per second: 84.8629MB
  User time: 0.060u
  Elapsed time: 0:01.049
  Version: ImageMagick 6.9.12-64 Q16 aarch64 17467 https://legacy.imagemagick.org
```

Using other tools such as Mac Preview, GraphicConverter and Photoshop and ImageJ, I can open the file and stretch the dynamic range and see the data.  It looks as follows from Photoshop stretched and converted to PNG

![mystery](https://user-images.githubusercontent.com/13458218/192413823-2d1705fa-4acf-4d90-a5ca-759395f74e06.png)

**Comment by jmilbrandt2** [comment]
The Java Library ImageJ is able to handle this but I can't find a C# library that can handle these images and my requirements say I must use C#. This Image is taken by a major Commercial product and millions of these images are generated daily so it would be a huge help

**Comment by fmw42** [comment]
Can you identify the commercial product that took the image?   It might help the IM developers.

**Comment by jmilbrandt2** [comment]
This is coming from a microscope used in research science at a major univsersity. I don't have the exact specs they'd be at another lab. I do know that it's a pretty common scope. Again I don't know if they are following the tiff specification but I am just looking for any possible way to view this Image in C# or in ImageMagick, I do not have control over these images, they are sent in bulk, large numbers of them, so I can't alter anything about them they come to me as they are. I typically use ImageJ to mess around with them on an individual basis so there has never been a problem. We are now trying to automate this proccess If this was something new I would just build it in Java and use ImageJ's plugin, however the C# application we use for this type of thing is long-standing and although I can download different versions it seems like ImageSharp and ImageMagick are both doing the same thing with this Tiff, I see it in only black and white, but it should be gray-scale and IT IS a grayscale image. If it is Tif is there any other operation I can perform on it to make it viewable?

**Comment by fmw42** [comment]
Is the microscope software doing any post processing before saving to TIF?  Is it actually saved as tif or is it converted from some proprietary format to tif?

If this is a bug in Imagemagick that can be fixed and not a bug in libtiff which Imagemagick uses to read tiff, then Imagemagick has Magick.Net software that does use C#. So it should work when fixed.  But Imagemagick use libtiff to read tiffs, so the bug may be in libtiff. 

Nevertheless, the IM developers will need to look into it for you.

**Comment by fmw42** [comment]
Can your microscope output to 16-bit PNG?

**Comment by fmw42** [comment]
Using

`tiffinfo -Dd mystery.tif`

I can see non-zero values. So I suspect libtiff can read the file correctly.  So I suspect a possible bug in IM.

**Comment by snibgo** [comment]
I confirm that pre-built IM v7.1.0-49 on Windows 8.1 can read mystery.tif, and thinks all pixels are black. Gimp and tiffcp can read the file, and thinks many pixels are shades of gray.

So a simple workaround is:
```
tiffcp mystery.tif tmp.tif
```
... than then process tmp.tif with IM, doing whatever is wanted.

This suggests that mystery.tif contains something weird. Perhaps the file does not comply with TIFF standards, or tifflib has a bug, or IM has a bug.

**Comment by fmw42** [comment]
I tested IM 6.9.10.82 

`convert mystery.tif -auto-level x.png`

and IM 7.1.0.32

`magick mystery.tif -auto-level x.png`

and they work fine. 

![x](https://user-images.githubusercontent.com/13458218/192591589-b3c7bcf5-d935-4859-9eb8-3abde4da8d3d.png)

**So there is a bug introduced after 6.9.10.82 or 7.1.0.32**

**Comment by dlemstra** [comment]
Are you sure about those version numbers Fred? On Windows with version 7.1.0-32 I still get a completely black image.

**Comment by jmilbrandt2** [comment]
> Is the microscope software doing any post processing before saving to TIF? Is it actually saved as tif or is it converted from some proprietary format to tif?
> 
> If this is a bug in Imagemagick that can be fixed and not a bug in libtiff which Imagemagick uses to read tiff, then Imagemagick has Magick.Net software that does use C#. So it should work when fixed. But Imagemagick use libtiff to read tiffs, so the bug may be in libtiff.
> 
> Nevertheless, the IM developers will need to look into it for you.

Unknown I apologize but 

> Can your microscope output to 16-bit PNG?

Unfortunately the microscope only outputs in this format and takes thousands and thousands of pictures very quickly. I wish I knew a little more, it's a General Electric Microscope, not sure of the exact version. It only outputs Tiff, I suspect cheaper versions of the microscope output 8 bit Tiffs but the entire point of the more expensive Microscope is the greater resolution. It's possible there is a conversion from a proprietary format but I don't know enough about the Scope to know exactly how it operates under the hood. 

most scientific software (Incarta, Adobe Photoshop, ImageJ, Mac Preview, even GIMP if I change the dynamic range enough) loads this photo without a problem, I really like ImageMagick software and it's really assisted our laboratory.

we are trying to use A.I. models to catch Neurodegenerative diseases like Alzehiemers and Parkinsons, so it would help use tremendously if we didn't have to use another programming language. Most of our people aren't coders or that isn't what they specialize in, so writing our own software for some kind of conversion is beyond our resources.

**Comment by jmilbrandt2** [comment]
I am going to try to find out more about the microscope specifications

**Comment by snibgo** [comment]
Some more data points:

IM v7.1.0-20 (Q32, HDRI), built with Cygwin tools, thinks mystery.tif is all black.

IM 7.0.9-17 successfully reads the file.
```
%IMG70917%magick mystery.tif -auto-level -resize 600 x.png
```

![x](https://user-images.githubusercontent.com/33812368/192625742-b70551bb-1865-456e-932f-dc1ed68fccf5.png)

**Comment by fmw42** [comment]
> Are you sure about those version numbers Fred? On Windows with version 7.1.0-32 I still get a completely black image.

Yes, I double checked and it does work on 7.1.0.32 on Mac.

**Comment by fmw42** [comment]
Message from dlemstra,

> this image does not have TIFFTAG_ROWSPERSTRIP

and IM defaults to read it with a generic method

But he is working on a possible fix.

**Comment by jmilbrandt2** [comment]
I really appreciate the work, I was able to find out the Microscope model is a GE InCell 6500 HS, but we definitely can't change how it exports

here are two more images. White and black dots no grayscale

https://drive.google.com/file/d/1BFcM4FERPPMGG83tU6bgFQI1MqJzz1Ii/view?usp=sharing
https://drive.google.com/file/d/1zpKIb61TYfJSenZ2HHB_D7WL1X86dwtE/view?usp=sharing

**Comment by fmw42** [comment]
Dirk,

Exiftool reports rowsperstrip of 64.

```
---- ExifTool ----
    - ExifToolVersion                 : 12.44
---- System ----
    - FileName                        : mystery.tif
    - Directory                       : .
    - FileSize                        : 75872
    - FileModifyDate                  : 2022:09:26 17:57:01-07:00
    - FileAccessDate                  : 2022:09:26 21:43:41-07:00
    - FileInodeChangeDate             : 2022:09:26 17:57:14-07:00
    - FilePermissions                 : 100644
---- File ----
    - FileType                        : TIFF
    - FileTypeExtension               : TIF
    - MIMEType                        : image/tiff
    - ExifByteOrder                   : II
---- IFD0 ----
  254 SubfileType                     : 0
  256 ImageWidth                      : 2040
  257 ImageHeight                     : 2040
  258 BitsPerSample                   : 16
  259 Compression                     : 5
  262 PhotometricInterpretation       : 1
  273 StripOffsets                    : (Binary data 191 bytes, use -b option to extract)
  274 Orientation                     : 1
  277 SamplesPerPixel                 : 1

  278 RowsPerStrip                    : 64  <------ See Here

  279 StripByteCounts                 : (Binary data 155 bytes, use -b option to extract)
  282 XResolution                     : 72
  283 YResolution                     : 72
  296 ResolutionUnit                  : 2
  305 Software                        : Adobe Photoshop 23.5 (Macintosh)
  306 ModifyDate                      : 2022:09:26 17:57:01
---- XMP-x ----
    - XMPToolkit                      : Adobe XMP Core 7.2-c000 79.1b65a79b4, 2022/06/13-22:01:01
---- XMP-xmp ----
    - CreatorTool                     : Adobe Photoshop 23.5 (Macintosh)
    - CreateDate                      : 2022:09:26 17:42:39-07:00
    - ModifyDate                      : 2022:09:26 17:57:01-07:00
    - MetadataDate                    : 2022:09:26 17:57:01-07:00
---- XMP-dc ----
    - Format                          : image/tiff
---- XMP-photoshop ----
    - ColorMode                       : 1
---- XMP-xmpMM ----
    - InstanceID                      : xmp.iid:127d14ef-84ff-4d04-a232-52149a4b9e90
    - DocumentID                      : xmp.did:127d14ef-84ff-4d04-a232-52149a4b9e90
    - OriginalDocumentID              : xmp.did:127d14ef-84ff-4d04-a232-52149a4b9e90
    - HistoryAction                   : created
    - HistoryInstanceID               : xmp.iid:127d14ef-84ff-4d04-a232-52149a4b9e90
    - HistoryWhen                     : 2022:09:26 17:42:39-07:00
    - HistorySoftwareAgent            : Adobe Photoshop 23.5 (Macintosh)
---- XMP-tiff ----
    - ImageWidth                      : 2040
    - ImageHeight                     : 2040
    - BitsPerSample                   : 16
    - Compression                     : 5
    - PhotometricInterpretation       : 1
    - Orientation                     : 1
    - SamplesPerPixel                 : 1
    - PlanarConfiguration             : 1
    - XResolution                     : 72
    - YResolution                     : 72
    - ResolutionUnit                  : 2
---- XMP-exif ----
    - ColorSpace                      : 65535
    - ExifImageWidth                  : 2040
    - ExifImageHeight                 : 2040
---- Photoshop ----
 1061 IPTCDigest                      : 00000000000000000000000000000000
 1082 PrintInfo2                      : ...printOutput.PstSbool.InteenumInteClrm.printSixteenBitbool.printerNameTEXT..printProofSetupObjc.Proof Setup.proofSetup.Bltnenum.builtinProof.proofCMYK
 1083 PrintStyle                      : ...printOutputOptions.CptnboolClbrboolRgsMboolCrnCboolCntCboolLblsboolNgtvboolEmlDboolIntrboolBckgObjc.RGBC.Rd  doub@o?Grn doub@o?Bl  doub@o?BrdTUntF#RltBld UntF#RltRsltUntF#Pxl@R.vectorDatabool.PgPsenumPgPsPgPCLeftUntF#RltTop UntF#RltScl UntF#Prc@Y.cropWhenPrintingbool.cropRectBottomlong.cropRectLeftlong.cropRectRightlong.cropRectToplong
    0 XResolution                     : 72
    2 DisplayedUnitsX                 : 1
    4 YResolution                     : 72
    6 DisplayedUnitsY                 : 1
    0 PrintStyle                      : 0
    2 PrintPosition                   : 0 0
   10 PrintScale                      : 1
 1037 GlobalAngle                     : 30
 1049 GlobalAltitude                  : 30
 1011 PrintFlags                      : 0 0 0 0 0 0 0 0 1
10000 PrintFlagsInfo                  : ..
 1012 BW_HalftoningInfo               : 5.-..
 1015 BW_TransferFunc                 : ??????????????????????.?
 1032 GridGuidesInfo                  : ..@.@
 1092 Photoshop_0x0444                : ..@.@
 1054 URL_List                        : 
   20 SlicesGroupName                 : mystery
   24 NumSlices                       : 1
    4 PixelAspectRatio                : 1
 1041 ICC_Untagged                    : 1
 1044 IDsBaseValue                    : 1
 1036 PhotoshopThumbnail              : (Binary data 1514 bytes, use -b option to extract)
    4 HasRealMergedData               : 1
    5 WriterName                      : Adobe Photoshop
    9 ReaderName                      : Adobe Photoshop 2022
---- ExifIFD ----
40961 ColorSpace                      : 65535
40962 ExifImageWidth                  : 2040
40963 ExifImageHeight                 : 2040
---- Composite ----
    - ImageSize                       : 2040 2040
    - Megapixels                      : 4.1616

```

**Comment by dlemstra** [comment]
As you might have noticed I pushed a patch to resolve this last night. You still need to `-auto-level` the image but I am getting the following output from the two extra files that were added:

image2.tif:
![image2](https://user-images.githubusercontent.com/10426229/193143618-a55601ca-320a-428f-b321-80b0d1226008.png)

image3.tif
![image3](https://user-images.githubusercontent.com/10426229/193143703-978352ae-15ed-4564-b2c5-d6cf5241ebc8.png)

This fix will also become available in the next version of Magick,NET.

**Comment by jmilbrandt2** [comment]
I just wanted to thank dlemstra for his work related to this. Hopefully this research will help a lot of sick people in the future. Many Universities are Microsoft shops and currently no open source or even semi-open source C# library (including ImageSharp) supports images from these types of microscopes, Supporting images from this and other advanced GE microscopes that output in this format would result in a wide range of new possibilities being open to us and dozens of other laboratories like us, not many universities have active Java programmers embedded in their Genetics or Neuroscience departments so this will likely make ImageMagick the default tool for this type of work in the C# language.

**Comment by jdmsolarius** [comment]
I went ahead and compiled the new code with your fix in it from source, and am using  it in a simple project and I'm still getting that exact same issue. Can you confirm when you grab this image. Here is the code i'm using to try and view it, and all I can see on this one is black i've tried autoleveling, grayscaling and setting the bit depth. Did you have to do anything special to get those to show up?

![image](https://user-images.githubusercontent.com/12174361/193994299-41f6e5ae-f576-4fc9-9a8b-1a46dfe11168.png)

**Comment by jdmsolarius** [comment]
I know nothing is garunteed to work until a release so if it's something that's just waiting until release it's no big deal at all I just wanted to make sure I wasn't doing something incorrectly. I used Magick.Native and created a key, went through the steps. I just want to make sure that when the next release does come it'll work.

**Comment by dlemstra** [comment]
If it would help I can publish a new release of Magick.NET that includes this fix tomorrow.

**Comment by jdmsolarius** [comment]
that would help tremendously, I can't thank you enough. It would help us with our research a lot

**Comment by jdmsolarius** [comment]
Can't thank you enough

**Comment by jdmsolarius** [comment]
We've really benefited from this library a lot so I really appreciate you
making this release happen.
