### ISSUE TITLE
Documentation: fix -identify description

### ISSUE THREAD

**Issue by greatvovan** [ImageMagick/ImageMagick#6635]
### ImageMagick version

7.1.1-15

### Operating system

MacOS

### Operating system, version and so on

13.5.2 (22G91)

### Description

The documentation [says](https://imagemagick.org/script/command-line-options.php#identify):

> This information is printed: image scene number; image name; image size; the image class (DirectClass or PseudoClass); the total number of unique colors; and the number of seconds to read and transform the image. Refer to [MIFF](https://imagemagick.org/script/miff.php) for a description of the image class.
If [-colors](https://imagemagick.org/script/command-line-options.php#colors) is also specified, the total unique colors in the image and color reduction error values are printed. Refer to [color reduction algorithm](https://imagemagick.org/script/quantize.php) for a description of these values.

When trying the command, the output it gives looks like this:

`IMG_1954.jpg JPEG 4032x3024 4032x3024+0+0 8-bit sRGB 4.97766MiB 0.180u 0:00.197`

I am trying to match what I see with the documentation:

| Documented | Real |
| --- | --- |
| image scene number | **[missing]** |
| image name | IMG_1954.jpg |
| **[Image format]** | JPEG |
| image size | 4032x3024 |
| **[???]** | 4032x3024+0+0 |
| **[color depth]** | 8-bit |
| **[color space]** | sRGB |
| **[file size]** | 4.97766MiB |
| the image class (DirectClass or PseudoClass) | **[missing]** |
|  the total number of unique colors | **[missing]** |
| the number of seconds to read and transform the image | 0.180u 0:00.197 |

**Color note**
The reference about total number of colors in the first paragraph is misleading as it makes one think the information is always shown. The second paragraph explains when exactly it is shown, so the mentioning in the first paragraph is redundant.

### Suggestions
1. Remove the missing items from the documentation or explain the conditions under which they are shown.
2. Document the extra items marked with square brackets.
3. Explain time indication. Do I understand it right that in my case it was 180 ms of user time and 197 ms of all time? If so, why are two different formats used? Maybe use seconds with fractions in both?
4. Remove mentioning of color from the first paragraph or add a note that its appearance is conditional.

### Steps to Reproduce

`magick img.jpg -identify null:`
Where img.jpg is any image.

**Comment by urban-warrior** [comment]
We updated the docs as you recommended.  If we missed anything, let us know.

**Comment by greatvovan** [comment]
Thanks for a quick reply.
Yes, some items are still missing, please see below.

| Documented | Real |
| --- | --- |
| image scene number (if its not zero) | |
| image name | IMG_1954.jpg |
| **-->Image format** | JPEG |
| image size | 4032x3024 |
| virtual page offset | 4032x3024+0+0 |
| **-->color depth** | 8-bit |
| **-->color space** | sRGB |
| **-->file size** | 4.97766MiB |
| consumed user time | 0.180u |
| elapsed time | 0:00.197 |

I am not sure if "file size" a good description, as it may be an intermediate state of processing existing only in memory. "Image length"? Please specify a description of your preference.

A side question: I did not notice any changes in `www/command-line-options.html`. Is you documentation unlinked from source control? I am newbie here.

**Comment by snibgo** [comment]
The documentation says:
> This information is printed: image scene number ...

I suggest inserting "by default":
> This information is printed by default: image scene number ...

I suggest this is also added:
> If `-format` precedes this option, the format string will be expanded instead of the default information.

**Comment by greatvovan** [comment]
I agree, referencing `-format` would be very useful here.

**Comment by urban-warrior** [comment]
Added your recommendations, let us know if we missed anything.

**Comment by greatvovan** [comment]
That looks great to me, thank you @urban-warrior.
Back to my source control question, are you versioning the documentation?

**Comment by urban-warrior** [comment]
The documentation has its own Github repo for source control.  However, for versioning, we have 6 and 7 but do not version with minor or patch #'s like we do for the ImageMagick source code repo.
