### ISSUE TITLE
"Ignoring invalid time value" error is not solved

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#685]
Discussion also [here](http://www.imagemagick.org/discourse-server/viewtopic.php?t=32505). This bug still exists in 7.0.6.7 and 6.9.9-7. 

**This bug appears only at certain time of day!**  Using OS-X Sierra. Currently it is 2.30pm Amsterdam time and the bug does not appear. However if I set the time on my clock to 10.30pm, I immediately get this error when read + writing a png file.

Perhaps the problem is triggered when the UTC date is different from the local date?

Probably introduced [here](https://github.com/ImageMagick/ImageMagick/commit/0dd3a0c4e855ef210a336e969235b95cc6e285e6#diff-06e0c72bb0a365a2fa4145b89e0a750a) or [here](https://github.com/ImageMagick/ImageMagick/commit/aff93388c39c1eb89600129e238206129f7cc12d#diff-06e0c72bb0a365a2fa4145b89e0a750a). @glennrp can you have a look?

**Comment by glennrp** [comment]
Sorry I have been busy with some libpng issues, getting a new set of RC
releases out.  I'll try to have a look today.

**Comment by glennrp** [comment]
It's a problem with the offset: 2017-08-19T09:31:15-04:00
IM is looking or :04:00 instead of -04:00
I have to contend with military timezones (offset Z) too.
I'll post a fix later today.

**Comment by glennrp** [comment]
Having some trouble debugging.  It seems that setting TZ on Ubuntu does not have the desired effect:

```
for TIMEZONE in UTC AMS PDT EDT IST
do
TZ=$TIMEZONE export TZ
date
done
Sat Aug 19 14:34:02 UTC 2017
Sat Aug 19 14:34:02 AMS 2017
Sat Aug 19 14:34:02 PDT 2017
Sat Aug 19 14:34:02 EDT 2017
Sat Aug 19 14:34:02 IST 2017

```
Note that "date" reports the desired timezone but doesn't actually convert the time.

**Comment by glennrp** [comment]
OK never mind that. I forgot that TZ needs offsets.  If I write
`for TIMEZONE in UTC0 AMS0 PDT8 EDT4 IST18.5`
it works:
```
Sat Aug 19 15:01:12 UTC 2017
Sat Aug 19 15:01:12 AMS 2017
Sat Aug 19 07:01:12 PDT 2017
Sat Aug 19 11:01:12 EDT 2017
Fri Aug 18 20:31:12 IST 2017

```

**Comment by glennrp** [comment]
Fixed in IM7: commit 295c896a502167c6322f1ec4740723857a7f9847

**Comment by jeroen** [comment]
Thank you for the quick fix! Hopefully this will make it into the next release of IM6 soon :)

**Comment by jeroen** [comment]
I think your commit on the IM6 branch https://github.com/ImageMagick/ImageMagick/commit/1f54a128c8bb14e5419e58ce68b096d39fc2dd40 may have unintentionally reverted https://github.com/ImageMagick/ImageMagick/commit/6519c467c9577ac963e0e44f8f47641fb24c192d ?

**Comment by glennrp** [comment]
Yes, fixed now in both IM6 and IM7.

**Comment by sf-butdim** [comment]
Hi folks, this bug is still present on **Mac OS X Sierra v10.12.5 with ImageMagick v7.0.7** (this is the latest version available via homebrew).

Yesterday somwhen between 23:00 and 23:30 I was getting the same error which spontaneously gone around 23:30.

Can you please investigate? This is **VERY** annoying.

Many thanks in advance.

**Comment by glennrp** [comment]
Please run with "-debug coder" and show us the line that begins "Date format ..."

**Comment by sf-butdim** [comment]
@glennrp do you mean I need to run it now or when the problem occurs again? Because this happens quite randomly as you know. Please confirm.

**Comment by dlemstra** [comment]
You might be able to force the problem again by changing the time on your machine. If you can please post the output as requested by @glennrp.

**Comment by glennrp** [comment]
Just run it now so I can see what your date format looks like.

**Comment by sf-butdim** [comment]
@dlemstra thank you for quick tipp, I'll give it a try.

@glennrp I'll check this tonight from my private laptop (currently I'm on working one).

I'll update this issue tonight, thank you for help guys.

**Comment by sf-butdim** [comment]
Good evening folks, it just happened to me again between 22:50 and 23:10. Unfortunately I was only able to get the debug stack trace now, when it's back to normal and working. I hope this helps, if not please ping me and I'll try to reproduce the problem tomorrow evening.

`convert -debug Coder img1.png img2.png
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadPNGImage/4202/Coder
  Enter ReadPNGImage()
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/2237/Coder
    Enter ReadOnePNGImage()
    IM version     = 7.0.7-0
    Libpng version = 1.6.32
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/2250/Coder
      Zlib version   = 1.2.8
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/2254/Coder
        running with   1.2.5
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/2282/Coder
      Before reading:
      image->alpha_trait=0
      image->rendering_intent=2
      image->colorspace=23
      image->gamma=0.454545
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/2585/Coder
      PNG width: 1280, height: 4327
    PNG color_type: 2, bit_depth: 8
    PNG compression_method: 0
    PNG interlace_method: 0, filter_method: 0
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/2855/Coder
      Setting sRGB as if in input
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/3175/Coder
      image->gamma=0.454545
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/3201/Coder
      image->colorspace=23
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/3355/Coder
      Reading PNG IDAT chunk(s)
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/3379/Coder
      Converting PNG pixels to pixel packets
2017-09-11T23:25:36+02:00 0:00.010 0.000u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/3453/Coder
      Looking for cheap transparent pixel
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/3696/Coder
      No transparent pixel was found
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/3721/Coder
    image->storage_class=1

2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/ReadOnePNGImage/4155/Coder
    exit ReadOnePNGImage()
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/ReadPNGImage/4287/Coder
    page.w: 0, page.h: 0,page.x: 0, page.y: 0.
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/ReadPNGImage/4291/Coder
    image->colorspace: 23
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/ReadPNGImage/4296/Coder
  exit ReadPNGImage()
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WritePNGImage/11982/Coder
  Enter WritePNGImage()
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WritePNGImage/12574/Coder
    Chunks to be excluded from the output png:
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8395/Coder
    Enter WriteOnePNGImage()
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8430/Coder
      IM version     = 7.0.7-0
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8432/Coder
      Libpng version = 1.6.32
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8439/Coder
      Zlib version   = 1.2.8
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8443/Coder
        running with   1.2.5
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8611/Coder
      image->storage_class=DirectClass
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8616/Coder
      image->taint=MagickFalse
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8619/Coder
      image->gamma=0.454545
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8870/Coder
      Enter BUILD_PALETTE:
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8875/Coder
        image->columns=1280
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8877/Coder
        image->rows=4327
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8879/Coder
        image->alpha_trait=0
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8881/Coder
        image->depth=8
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8917/Coder
        image->colors=0
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8921/Coder
          (zero means unknown)
2017-09-11T23:25:36+02:00 0:00.130 0.110u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/8925/Coder
        Regenerate the colormap
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9039/Coder
        Check colormap for background (65535,65535,65535)
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9065/Coder
        No room in the colormap to add background color
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9074/Coder
        image has more than 256 colors
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9268/Coder
        image->colors=0
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9292/Coder
        number_transparent     = 0
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9306/Coder
        number_opaque          > 256
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9310/Coder
        number_semitransparent = 0
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9327/Coder
        At least one pixel or the background is non-gray
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9330/Coder
      Exit BUILD_PALETTE:
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9863/Coder
      width=1280
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9865/Coder
      height=4327
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9867/Coder
      image_matte=0
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9869/Coder
      image->depth=8
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9871/Coder
      Tentative ping_bit_depth=8
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9956/Coder
      Setting up bKGD chunk (1)
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9958/Coder
        background_color index is 0
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/9962/Coder
      ping_bit_depth=8
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10100/Coder
    Selecting PNG colortype:
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10158/Coder
      Selected PNG colortype=2
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10195/Coder
      Number of colors: 0
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10198/Coder
      Tentative PNG bit depth: 8
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10210/Coder
      Tentative PNG color type: RGB (2)
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10215/Coder
      image_info->type: 0
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10218/Coder
      image_depth: 8
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10221/Coder
      image->depth: 8
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10225/Coder
      ping_bit_depth: 8
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10629/Coder
      PNG color type: RGB (2)
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10637/Coder
    Setting up deflate compression
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10640/Coder
      Compression buffer size: 32768
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10647/Coder
      Compression mem level: 9
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10726/Coder
      Compression level:    7
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10735/Coder
    Setting up filtering
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10739/Coder
      Base filter method: ADAPTIVE
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/10874/Coder
    Writing PNG header chunks
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11012/Coder
    Setting up gAMA chunk
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11040/Coder
    Setting up cHRM chunk
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11056/Coder
      Setting up bKGD chunk
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11058/Coder
        background color = (255,255,255)
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11063/Coder
        index = 0, gray=255
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11258/Coder
    Writing PNG image data
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11261/Coder
      Allocating 3840 bytes of memory for pixels
2017-09-11T23:25:36+02:00 0:00.170 0.160u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11465/Coder
      Writing row of pixels (3)
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11562/Coder
    Wrote PNG image data
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11565/Coder
      Width: 1280
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11568/Coder
      Height: 4327
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11577/Coder
      PNG bit-depth written: 8
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11586/Coder
      PNG color-type written: 2
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11589/Coder
      PNG Interlace method: 0
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11651/Coder
    Setting up text chunk
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11654/Coder
      keyword: 'date:create'
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11651/Coder
    Setting up text chunk
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11654/Coder
      keyword: 'date:modify'
2017-09-11T23:25:37+02:00 0:00.620 0.600u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11727/Coder
    Writing PNG end info
2017-09-11T23:25:37+02:00 0:00.630 0.610u 7.0.7 Coder convert[4906]: png.c/WriteOnePNGImage/11795/Coder
    exit WriteOnePNGImage()
2017-09-11T23:25:37+02:00 0:00.630 0.620u 7.0.7 Coder convert[4906]: png.c/WritePNGImage/12639/Coder
  exit WritePNGImage()`

**Comment by glennrp** [comment]
The problem seems to be due to use of unsigned arithmetic in the timezone calculations.  Fixed in IM7 commit 43f1a508057b17408a12ca1cebe0dd362adecddd

**Comment by dlemstra** [comment]
@glennrp It appears this issue is still not resolved. You can force a failure with the following commands:

```
convert logo: -define date:modify=2017-09-10T20:35:00+03:30 test.png
convert logo: -define date:modify=2017-09-10T15:30:00+03:30 test.png
```

**Comment by sf-butdim** [comment]
@glennrp thank you for an update on that. When could we count this to be fixed? In the next released version?

**Comment by ferencbeutel** [comment]
at 22:00 GMT+2 this happened for me aswell today

**Comment by glennrp** [comment]
Your test is not failing for me with the GIT heads for im6 and im7.  However, test.png ends
up with a tIME chunk containing the current time not the defined time.

**Comment by dlemstra** [comment]
I just tested with the latest git head of IM7 and I get the following output:
```
I:\tiff\exif>convert logo: -define date:modify=2017-09-10T20:35:00+03:30 test.png
convert: Ignoring invalid time value `test.png' @ warning/png.c/MagickPNGWarningHandler/1744.
```

**Comment by glennrp** [comment]
Apparently I can't test in timezones other than my own.  I set the environment variable TZ but it seems to have little effect (It changes the format of the output of "date" but not the time).

**Comment by glennrp** [comment]
If you run with -debug coder, what does the "png_set_tIME" line look like?

**Comment by dlemstra** [comment]
I cannot reproduce it on the command line anymore. But I can force the exception by changing the code to this:
```
      else
        {
          (void) LogMagickEvent(CoderEvent,GetMagickModule(),
             "  Reset tIME in tainted image");

          SetImageProperty(image,"date:modify", "2017-09-10T20:35:00+03:30",exception);
          timestamp=GetImageProperty(image,"date:modify",exception);
        }
```

```
2017-09-12T23:35:56+02:00 0:01.037 0.703u 7.0.6 Coder convert[8956]: png.c/WriteOnePNGImage/11107/Coder
    Reset tIME in tainted image
2017-09-12T23:35:56+02:00 0:01.039 0.703u 7.0.6 Coder convert[8956]: png.c/write_tIME_chunk/8152/Coder
    Writing tIME chunk: timestamp property is      2017-09-10T20:35:00+03:30

2017-09-12T23:35:56+02:00 0:01.040 0.703u 7.0.6 Coder convert[8956]: png.c/write_tIME_chunk/8160/Coder
     Date format specified for png:tIME=2017-09-10T20:35:00+03:30
2017-09-12T23:35:56+02:00 0:01.041 0.703u 7.0.6 Coder convert[8956]: png.c/write_tIME_chunk/8162/Coder
        ret=8,y=2017, m=9, d=10, h=20, m=35, s=0, ah=3, as=30
2017-09-12T23:35:56+02:00 0:01.043 0.703u 7.0.6 Coder convert[8956]: png.c/write_tIME_chunk/8235/Coder
        png_set_tIME: y=2017, m=9, d=10, h=24, m=5, s=0, ah=3, am=30
```

**Comment by glennrp** [comment]
It is writing hour=24 while the maximum valid hour si 23.  Fixed in the git repos.

**Comment by glennrp** [comment]
You're right, minute=60 is also invalid.

**Comment by jeroen** [comment]
Has a new IM6 release with this fix been released yet?

**Comment by glennrp** [comment]
6.9.9-14 has the fix, I believe.

Glenn

**Comment by rickrich** [comment]
$ $HOME/proj/geo/mngca-newmap -agstatic -n
convert: Ignoring invalid time value `/tmp/geo22385-imap.png' @
warning/png.c/MagickPNGWarningHandler/1665.

# dnf list ImageMagick
ImageMagick.x86_64                   6.9.9.13-1.fc25                    @updates

**Comment by glennrp** [comment]
Please try 6.9.9-14

**Comment by laurentKTR** [comment]
Hi
i have the same concern with date : In france , the format is day/month/year
and today we are 13/10/2017 => 13 is an invalid month

Magick.NET-Q16-AnyCPU.dll
Additional information: Invalid date format specified for png
:tIME `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
@ error/png.c/write_tIME_chunk/8178

**Comment by glennrp** [comment]
I don't think that's something that can be detected or fixed in the PNG encoder. It needs to be fixed wherever SetImageProperty() records the timestamp.

**Comment by laurentKTR** [comment]
the strange thing is that i'm getting this error only when i apply BrightnessContrast with percentage on black and white points. 
i have tried other methods like InverseLevel/ContrastStretch and no error occurs when i save the image
using a header reader i got this
exif:DateTime: 2007:11:26 14:05:36 => strange format for a date
PNG-tEXt

**Comment by laurentKTR** [comment]
i'm adding if it can help you that if i'm calling another method before BrightnessContrast, 
then this error is not thrown
ex :
magImg.AutoLevel();
magImg.BrightnessContrast(new Percentage(-10), new Percentage(-30));
=> OK
only
magImg.BrightnessContrast(new Percentage(-10), new Percentage(-30));
=> KO

**Comment by dlemstra** [comment]
@laurentKTR It looks like you are reading a file that has an incorrect PNG timestamp. So it looks like you are experiencing a different issue. I will close this issue now. If you need more help feel free to start a new issue here or in the Magick.NET project.
