### ISSUE TITLE
Possible bug -sparse-color as fill operator

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7863]
### ImageMagick version

7.1.1.43

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

I cannot reproduce the example from Anthony's pages at https://usage.imagemagick.org/canvas/#sparse_fill. 

(Note I did modify my policy.xml file to give read|write permissions for @*)

Input:

![sparse_source](https://github.com/user-attachments/assets/153992a4-44b7-4cc5-aa98-af4e4199d769)

 ```
 magick sparse_source.gif txt:- |\
 sed '1d; / 0) /d; s/:.* /,/;' |\
 magick sparse_source.gif -alpha off \
 -sparse-color shepards '@-' sparse_fill.png
```

![sparse_fill](https://github.com/user-attachments/assets/b3fc0e02-84b4-41c7-920c-48aa0f57e750)

But should look like

![sparse_fill-1](https://github.com/user-attachments/assets/04241d67-ec9c-41be-bf86-25d77b0d3be9)

### Steps to Reproduce

See above

### Images

See above

**Comment by dlemstra** [comment]
Thanks for reporting this Fred. I just pushed a patch to update our documentation:

```
magick sparse_source.gif sparse-color:- |\
    magick sparse_source.gif -alpha off \
            -sparse-color shepards '@-' sparse_fill.png
```

People should use `sparse-color:` instead of `txt:`.

**Comment by fmw42** [comment]
But why does Anthony's command not work any longer.  I even tried with convert and it still does not work.

**Comment by dlemstra** [comment]
At some point the output of `txt:` was changed so this no longer worked and that is probably why `sparse-color:` was added.

**Comment by fmw42** [comment]
Sorry, but sparse-color: was added for other reasons.  txt: should work if the sed etc that Anthony used parses it correctly.  I will check that to see if it produces correct values for input to -sparse-color.  Let me get back to you about it.  Sparse-color: was likely added much after Anthony created that example and txt: was the only thing available with filtering from sed

**Comment by fmw42** [comment]
OK, this now works. I had to remove all the transparent pixels and reformat a list to a string.

```
magick sparse_source.gif txt:- |\
sed '1d; / 0) /d; s/:.* /,/;' | grep -v 'none' | tr '\012' ' ' |\
magick sparse_source.gif -alpha off \
-sparse-color voronoi '@-' sparse_voronoi.png
```

However, this is simpler:

```
magick sparse_source.gif sparse-color:- |\
magick sparse_source.gif -alpha off \
-sparse-color voronoi '@-' sparse_voronoi.png
```

Anthony's page for this example can be edited to use either or show both

**Comment by dlemstra** [comment]
I have already edited the page to use the second example because that seemed simpler to me.
